### ISSUE TITLE
Created project can not be imported as plugin

### ISSUE THREAD

**Issue by benjohnde** [Ingwersaft/ValueClassGenerator#19]
Seems that we have the following issues:

- My IntelliJ only accepts jar files.
- Currently, the classes lie in the `classes` directory and thus are not detected. Putting them straight in the root directory fixes the problem.
- The description section in the `plugin.xml` is wrapped in a CDATA-tag, which seems to be removed after the plugin is compiled. Thus, IntelliJ can not parse the xml file.
- In the current downloadable build (from releases), the `<idea-version since-build='...'>` is too high.

Currently, I have no clue why the heck the `plugin.xml` is modified in that way.

**Comment by Ingwersaft** [comment]
Try it again :+1:

**Comment by benjohnde** [comment]
Check, now it works smoothly. After `gradle buildPlugin` I can use the generated `ValueClassGenerator.zip` located in `./build/distributions`. Cheers!
